export const FIELD_REQURED = 'Поле обязательно для заполнения'
export const MAX_LENGTH_FORTY = 'Максимальная длина 40 символов'
export const MIN_LENGTH_TWO = 'Минимальная длина 2 символа'
export const MIN_LENGTH_SEVEN = 'Минимальная длина 7 символов'
export const EMAIL_REQUIRED = 'Введите email'
