export const FIELD_REQURED = 'Поле обязательно для заполнения'
export const KEYWORD_REQUIRED = 'Введите ключевое слово'
export const MAX_LENGTH_FORTY = 'Максимальная длина 40 символов'
export const MIN_LENGTH_TWO = 'Минимальная длина 2 символа'
export const MIN_LENGTH_SEVEN = 'Минимальная длина 7 символов'
export const NAME_INCORRECT = 'Имя должно содержать только буквы, дефис и пробел'
export const EMAIL_INCORRECT = 'Некорректный email'
